---
apiVersion: spinnaker.adobe.com/alpha1
kind: Pipeline
metadata:
  name: parallelPipes
  application: swinchuuidtest
spec:
# TODO auto index all pipelines in an application
  index: 3
  keepWaitingPipelines: false
  limitConcurrent: true
  spelEvaluator: v4
  stages:
    # Presume 1:1 bake to deploy stage ratio
    - name: "Bake 1"
      type: bakeManifest
      namespace: "swinch"
      outputName: redis
      requisiteStageRefIds: []
      templateRenderer: HELM2
      inputArtifacts:
        - account: stable
          artifact:
            name: redis
            type: helm/chart
            version: 10.5.7
      expectedArtifacts:
        - displayName: redis
          matchArtifact:
            artifactAccount: embedded-artifact
            name: redis
            type: embedded/base64
    
    - name: "Bake 2"
      type: bakeManifest
      namespace: "swinch"
      outputName: redis
      requisiteStageRefIds: []
      templateRenderer: HELM2
      inputArtifacts:
        - account: stable
          artifact:
            name: redis
            type: helm/chart
            version: 10.5.7
      expectedArtifacts:
        - displayName: redis
          matchArtifact:
            artifactAccount: embedded-artifact
            name: redis
            type: embedded/base64
    
    - name: "Deploy 1 in MyCluster1 from parallelPipes"
      # We loop over the deploy stages, but as we presume a 1:1 ratio to bake we can use the deploy index to refer back
      # to the bake index
      # Add one to the index, go template starts from 0, spinnaker starts from 1
      requisiteStageRefIds:
        - 1
      type: deployManifest
      account: "test"
      cloudProvider: kubernetes
      namespaceOverride: "swinch"
      skipExpressionEvaluation: true
      source: artifact
    
    - name: "Deploy 2 in MyCluster2 from parallelPipes"
      # We loop over the deploy stages, but as we presume a 1:1 ratio to bake we can use the deploy index to refer back
      # to the bake index
      # Add one to the index, go template starts from 0, spinnaker starts from 1
      requisiteStageRefIds:
        - 2
      type: deployManifest
      account: "test"
      cloudProvider: kubernetes
      namespaceOverride: "swinch"
      skipExpressionEvaluation: true
      source: artifact
    
    - name: Delete (Manifest)
      requisiteStageRefIds:
      - 3
      - 4
      type: deleteManifest
      account:  "test"
      cloudProvider: kubernetes
      kinds:
        - statefulSet
        - configMap
        - secret
        - persistentVolumeClaim
        - service
      labelSelectors:
        selectors:
          - key: app
            kind: EQUALS
            values:
              - redis
      namespace: "swinch"
      mode: label
      options:
        cascading: true
  triggers: []
    


